"""coageneration: Chain-of-Action data generation for AI agents."""

from .core import (
    Action,
    ActionCategory,
    Asset,
    ChainStep,
    ConditionalBranch,
    CourseOfAction,
    Force,
    GameState,
    Policy,
    SelfPlayEngine,
    ToolCall,
    build_chain,
    compute_mef_score,
)
from .llm_policy import LLMPolicy
from .data import (
    make_action,
    make_asset,
    make_coa,
    make_coa_with_branch,
    make_cyber_ops_coa,
    make_game_state,
    make_info_ops_coa,
    make_logistics_coa,
)
from .evaluate import (
    action_diversity_score,
    chain_coverage_score,
    coa_diversity,
    episode_summary,
    gbc_score,
    nash_gap,
    robustness_score,
    tool_utilisation_rate,
)

__all__ = [
    "Action",
    "ActionCategory",
    "Asset",
    "ChainStep",
    "ConditionalBranch",
    "CourseOfAction",
    "Force",
    "GameState",
    "LLMPolicy",
    "Policy",
    "SelfPlayEngine",
    "ToolCall",
    "build_chain",
    "compute_mef_score",
    "make_action",
    "make_asset",
    "make_coa",
    "make_coa_with_branch",
    "make_cyber_ops_coa",
    "make_game_state",
    "make_info_ops_coa",
    "make_logistics_coa",
    "action_diversity_score",
    "chain_coverage_score",
    "coa_diversity",
    "episode_summary",
    "gbc_score",
    "nash_gap",
    "robustness_score",
    "tool_utilisation_rate",
]
